;; package
(el-get-bundle ag)
(el-get-bundle wgrep)
(el-get-bundle anything)
(el-get-bundle descbinds-anything)
(el-get-bundle auto-complete)
(el-get-bundle browse-kill-ring)
;(el-get-bundle flycheck)
(el-get-bundle git-gutter)
(el-get-bundle recentf-ext)
(el-get-bundle zlc)
(el-get-bundle undo-tree)
(el-get-bundle undohist)
(el-get-bundle dired+)
(el-get-bundle popup)
(el-get-bundle popwin)
(el-get-bundle expand-region)
(el-get-bundle smartparens)
(el-get-bundle ace-jump-mode)
(el-get-bundle rainbow-delimiters)
(el-get-bundle multiple-cursors)
(el-get-bundle smartrep)
(el-get-bundle auto-highlight-symbol)
(el-get-bundle highlight-symbol)
(el-get-bundle anzu)
(el-get-bundle anything-git-files)
(el-get-bundle exec-path-from-shell)
(el-get-bundle move-text)
(el-get-bundle volatile-highlights)
(el-get-bundle hlinum)
(el-get-bundle smooth-scroll)
(el-get-bundle yascroll)
(el-get-bundle magit)
(el-get-bundle smart-newline)
;(el-get-bundle helm)
;(el-get-bundle helm-open-github)
;(el-get-bundle powerline)
;(el-get-bundle key-chord)
;(el-get-bundle esup)
;(el-get-bundle pbcopy)
;(el-get-bundle quickrun)
;(el-get-bundle evil)
;(el-get-bundle elscreen)
;(el-get-bundle color-theme)

;; prog modes
(el-get-bundle coffee-mode)
(el-get-bundle go-mode)
(el-get-bundle js2-mode)
(el-get-bundle json-mode)
(el-get-bundle less-css-mode)
(el-get-bundle motion-mode)
(el-get-bundle puppet-mode)
(el-get-bundle rhtml-mode)
(el-get-bundle ruby-mode)
(el-get-bundle rspec-mode)
(el-get-bundle sass-mode)
(el-get-bundle slim-mode)
(el-get-bundle git-modes)
(el-get-bundle web-mode)
(el-get-bundle php-mode)
(el-get-bundle yaml-mode)
(el-get-bundle markdown-mode)
(el-get-bundle clojure-mode)
(el-get-bundle haskell-mode)

;; ruby
(el-get-bundle rubocop)
(el-get-bundle ruby-block)
(el-get-bundle ruby-end)
(el-get-bundle rbenv)
(el-get-bundle inf-ruby)
(el-get-bundle dgutov/robe)

;; go
(el-get-bundle go-autocomplete)


;;; Go
;(el-get-bundle go-mode)
;(el-get-bundle syohex/emacs-go-eldoc :name go-eldoc)
;(el-get-bundle elpa:golint)
;(el-get-bundle nsf/gocode :load-path ("emacs") :name go-autocomplete)
;;;(el-get-bundle nsf/gocode :load-path ("emacs-company") :name company-go)
;
;;; Python
;(el-get-bundle tkf/emacs-python-environment)
;(el-get-bundle tkf/emacs-jedi)
;;;(el-get-bundle syohex/emacs-company-jedi :name company-jedi)
;
;;; Perl
;(el-get-bundle hinrik/perl6-mode)
