;; https://github.com/mooz/emacs-zlc/issues/10
;; (require 'zlc)
;; (setq zlc-select-completion-immediately t)
;; (zlc-mode 1)
;; (let ((map minibuffer-local-map))
;;   (define-key map (kbd "<down>")  'zlc-select-next-vertical)
;;   (define-key map (kbd "<up>")    'zlc-select-previous-vertical)
;;   (define-key map (kbd "<right>") 'zlc-select-next)
;;   (define-key map (kbd "<left>")  'zlc-select-previous)
;;   (define-key map (kbd "C-c") 'zlc-reset)
;;   (define-key map (kbd "M-<tab>") 'zlc-select-previous)
;;   (define-key map (kbd "M-TAB") 'zlc-select-previous))
